
To connect to the compute node  on Ibex running your Jupyter server, 
you need to create an ssh tunnel from your local machine to login node on Ibex 
using the following command.

ssh -L 12815:cn605-21-l:12815 medinils@ilogin.ibex.kaust.edu.sa 

Next, you need to copy the second url provided below and paste it into the browser 
on your local machine.

[I 2023-08-18 04:44:01.314 ServerApp] Package jupyterlab took 0.0001s to import
[I 2023-08-18 04:44:14.558 ServerApp] Package dask_labextension took 13.2432s to import
[W 2023-08-18 04:44:14.559 ServerApp] A `_jupyter_server_extension_points` function was not found in dask_labextension. Instead, a `_jupyter_server_extension_paths` function was found and will be used for now. This function name will be deprecated in future releases of Jupyter Server.
[I 2023-08-18 04:44:15.575 ServerApp] Package jupyter_lsp took 1.0152s to import
[W 2023-08-18 04:44:15.575 ServerApp] A `_jupyter_server_extension_points` function was not found in jupyter_lsp. Instead, a `_jupyter_server_extension_paths` function was found and will be used for now. This function name will be deprecated in future releases of Jupyter Server.
[I 2023-08-18 04:44:15.676 ServerApp] Package jupyter_server_fileid took 0.0996s to import
[I 2023-08-18 04:44:15.794 ServerApp] Package jupyter_server_mathjax took 0.1167s to import
[I 2023-08-18 04:44:15.795 ServerApp] Package jupyter_server_proxy took 0.0001s to import
[I 2023-08-18 04:44:16.224 ServerApp] Package jupyter_server_terminals took 0.4280s to import
[I 2023-08-18 04:44:19.135 ServerApp] Package jupyter_server_ydoc took 2.9099s to import
[I 2023-08-18 04:44:20.679 ServerApp] Package jupyterlab_git took 1.5423s to import
[I 2023-08-18 04:44:20.680 ServerApp] Package nbclassic took 0.0000s to import
[W 2023-08-18 04:44:20.825 ServerApp] A `_jupyter_server_extension_points` function was not found in nbclassic. Instead, a `_jupyter_server_extension_paths` function was found and will be used for now. This function name will be deprecated in future releases of Jupyter Server.
[I 2023-08-18 04:44:20.827 ServerApp] Package nbdime took 0.0001s to import
[I 2023-08-18 04:44:20.827 ServerApp] Package notebook_shim took 0.0000s to import
[W 2023-08-18 04:44:20.828 ServerApp] A `_jupyter_server_extension_points` function was not found in notebook_shim. Instead, a `_jupyter_server_extension_paths` function was found and will be used for now. This function name will be deprecated in future releases of Jupyter Server.
[I 2023-08-18 04:44:46.988 ServerApp] Package panel.io.jupyter_server_extension took 26.1405s to import
[I 2023-08-18 04:44:46.989 ServerApp] dask_labextension | extension was successfully linked.
[I 2023-08-18 04:44:46.989 ServerApp] jupyter_lsp | extension was successfully linked.
[I 2023-08-18 04:44:47.200 ServerApp] jupyter_server_fileid | extension was successfully linked.
[I 2023-08-18 04:44:47.397 ServerApp] jupyter_server_mathjax | extension was successfully linked.
[I 2023-08-18 04:44:47.398 ServerApp] jupyter_server_proxy | extension was successfully linked.
[I 2023-08-18 04:44:47.595 ServerApp] jupyter_server_terminals | extension was successfully linked.
[I 2023-08-18 04:44:47.793 ServerApp] jupyter_server_ydoc | extension was successfully linked.
[I 2023-08-18 04:44:48.000 ServerApp] jupyterlab | extension was successfully linked.
[I 2023-08-18 04:44:48.000 ServerApp] jupyterlab_git | extension was successfully linked.
[I 2023-08-18 04:44:48.207 ServerApp] nbclassic | extension was successfully linked.
[I 2023-08-18 04:44:48.208 ServerApp] nbdime | extension was successfully linked.
[I 2023-08-18 04:44:59.556 ServerApp] notebook_shim | extension was successfully linked.
[I 2023-08-18 04:44:59.558 ServerApp] panel.io.jupyter_server_extension | extension was successfully linked.
[I 2023-08-18 04:45:03.861 ServerApp] notebook_shim | extension was successfully loaded.
[I 2023-08-18 04:45:03.864 ServerApp] dask_labextension | extension was successfully loaded.
[I 2023-08-18 04:45:03.912 ServerApp] jupyter_lsp | extension was successfully loaded.
[I 2023-08-18 04:45:03.913 FileIdExtension] Configured File ID manager: ArbitraryFileIdManager
[I 2023-08-18 04:45:03.913 FileIdExtension] ArbitraryFileIdManager : Configured root dir: /ibex/scratch/medinils/breast_data/bin
[I 2023-08-18 04:45:03.914 FileIdExtension] ArbitraryFileIdManager : Configured database path: /home/medinils/.local/share/jupyter/file_id_manager.db
[I 2023-08-18 04:45:03.917 FileIdExtension] ArbitraryFileIdManager : Successfully connected to database file.
[I 2023-08-18 04:45:03.918 FileIdExtension] ArbitraryFileIdManager : Creating File ID tables and indices with journal_mode = DELETE
[I 2023-08-18 04:45:03.920 FileIdExtension] Attached event listeners.
[I 2023-08-18 04:45:03.921 ServerApp] jupyter_server_fileid | extension was successfully loaded.
[I 2023-08-18 04:45:03.922 ServerApp] jupyter_server_mathjax | extension was successfully loaded.
[I 2023-08-18 04:45:05.688 ServerApp] jupyter_server_proxy | extension was successfully loaded.
[I 2023-08-18 04:45:05.697 ServerApp] jupyter_server_terminals | extension was successfully loaded.
[I 2023-08-18 04:45:05.699 ServerApp] jupyter_server_ydoc | extension was successfully loaded.
[I 2023-08-18 04:45:06.124 LabApp] JupyterLab extension loaded from /ibex/scratch/medinils/breast_data/env/lib/python3.8/site-packages/jupyterlab
[I 2023-08-18 04:45:06.124 LabApp] JupyterLab application directory is /ibex/scratch/medinils/breast_data/env/share/jupyter/lab
[I 2023-08-18 04:45:06.167 ServerApp] jupyterlab | extension was successfully loaded.
[I 2023-08-18 04:45:06.180 ServerApp] jupyterlab_git | extension was successfully loaded.
[I 2023-08-18 04:45:06.491 ServerApp] nbclassic | extension was successfully loaded.
[I 2023-08-18 04:45:09.320 ServerApp] nbdime | extension was successfully loaded.
[I 2023-08-18 04:45:09.324 ServerApp] panel.io.jupyter_server_extension | extension was successfully loaded.
[I 2023-08-18 04:45:09.327 ServerApp] Serving notebooks from local directory: /ibex/scratch/medinils/breast_data/bin
[I 2023-08-18 04:45:09.327 ServerApp] Jupyter Server 2.7.1 is running at:
[I 2023-08-18 04:45:09.327 ServerApp] http://cn605-21-l:12815/lab?token=3261b5cb3a05e3ef894a290ad7db72f4e49d1fc214e577e3
[I 2023-08-18 04:45:09.327 ServerApp]     http://127.0.0.1:12815/lab?token=3261b5cb3a05e3ef894a290ad7db72f4e49d1fc214e577e3
[I 2023-08-18 04:45:09.327 ServerApp] Use Control-C to stop this server and shut down all kernels (twice to skip confirmation).
[C 2023-08-18 04:45:09.356 ServerApp] 
    
    To access the server, open this file in a browser:
        file:///home/medinils/.local/share/jupyter/runtime/jpserver-151138-open.html
    Or copy and paste one of these URLs:
        http://cn605-21-l:12815/lab?token=3261b5cb3a05e3ef894a290ad7db72f4e49d1fc214e577e3
        http://127.0.0.1:12815/lab?token=3261b5cb3a05e3ef894a290ad7db72f4e49d1fc214e577e3
[I 2023-08-18 04:45:11.883 ServerApp] Skipped non-installed server(s): bash-language-server, dockerfile-language-server-nodejs, javascript-typescript-langserver, jedi-language-server, julia-language-server, pyright, python-lsp-server, r-languageserver, sql-language-server, texlab, typescript-language-server, unified-language-server, vscode-css-languageserver-bin, vscode-html-languageserver-bin, vscode-json-languageserver-bin, yaml-language-server
[W 2023-08-18 04:54:43.652 LabApp] Could not determine jupyterlab build status without nodejs
[W 2023-08-18 04:54:51.449 ServerApp] wrote error: 'No such file or directory: Scanpy/Tokio.ipynb'
    Traceback (most recent call last):
      File "/ibex/scratch/medinils/breast_data/env/lib/python3.8/site-packages/tornado/web.py", line 1786, in _execute
        result = await result
      File "/ibex/scratch/medinils/breast_data/env/lib/python3.8/site-packages/jupyter_server/services/contents/handlers.py", line 121, in get
        model = await ensure_async(
      File "/ibex/scratch/medinils/breast_data/env/lib/python3.8/site-packages/jupyter_core/utils/__init__.py", line 182, in ensure_async
        result = await obj
      File "/ibex/scratch/medinils/breast_data/env/lib/python3.8/site-packages/jupyter_server/services/contents/filemanager.py", line 861, in get
        raise web.HTTPError(404, "No such file or directory: %s" % path)
    tornado.web.HTTPError: HTTP 404: Not Found (No such file or directory: Scanpy/Tokio.ipynb)
[W 2023-08-18 04:54:51.586 ServerApp] 404 GET /api/contents/Scanpy/Tokio.ipynb?content=0&1692323690967 (e0cff5c1e766474f9e8aa8d378d5b591@10.109.65.8) 152.32ms referer=http://127.0.0.1:12815/lab
[W 2023-08-18 04:54:51.654 ServerApp] wrote error: 'No such file or directory: Scanpy/Stereoscope.ipynb'
    Traceback (most recent call last):
      File "/ibex/scratch/medinils/breast_data/env/lib/python3.8/site-packages/tornado/web.py", line 1786, in _execute
        result = await result
      File "/ibex/scratch/medinils/breast_data/env/lib/python3.8/site-packages/jupyter_server/services/contents/handlers.py", line 121, in get
        model = await ensure_async(
      File "/ibex/scratch/medinils/breast_data/env/lib/python3.8/site-packages/jupyter_core/utils/__init__.py", line 182, in ensure_async
        result = await obj
      File "/ibex/scratch/medinils/breast_data/env/lib/python3.8/site-packages/jupyter_server/services/contents/filemanager.py", line 861, in get
        raise web.HTTPError(404, "No such file or directory: %s" % path)
    tornado.web.HTTPError: HTTP 404: Not Found (No such file or directory: Scanpy/Stereoscope.ipynb)
[W 2023-08-18 04:54:51.673 ServerApp] 404 GET /api/contents/Scanpy/Stereoscope.ipynb?content=0&1692323690968 (e0cff5c1e766474f9e8aa8d378d5b591@10.109.65.8) 33.67ms referer=http://127.0.0.1:12815/lab
[W 2023-08-18 04:54:51.770 ServerApp] wrote error: 'No such file or directory: Scanpy/Preprocessing and clustering human crebellum data.ipynb'
    Traceback (most recent call last):
      File "/ibex/scratch/medinils/breast_data/env/lib/python3.8/site-packages/tornado/web.py", line 1786, in _execute
        result = await result
      File "/ibex/scratch/medinils/breast_data/env/lib/python3.8/site-packages/jupyter_server/services/contents/handlers.py", line 121, in get
        model = await ensure_async(
      File "/ibex/scratch/medinils/breast_data/env/lib/python3.8/site-packages/jupyter_core/utils/__init__.py", line 182, in ensure_async
        result = await obj
      File "/ibex/scratch/medinils/breast_data/env/lib/python3.8/site-packages/jupyter_server/services/contents/filemanager.py", line 861, in get
        raise web.HTTPError(404, "No such file or directory: %s" % path)
    tornado.web.HTTPError: HTTP 404: Not Found (No such file or directory: Scanpy/Preprocessing and clustering human crebellum data.ipynb)
[W 2023-08-18 04:54:51.788 ServerApp] 404 GET /api/contents/Scanpy/Preprocessing%20and%20clustering%20human%20crebellum%20data.ipynb?content=0&1692323690970 (e0cff5c1e766474f9e8aa8d378d5b591@10.109.65.8) 32.90ms referer=http://127.0.0.1:12815/lab
[W 2023-08-18 04:54:57.749 ServerApp] wrote error: 'No such file or directory: Scanpy/data'
    Traceback (most recent call last):
      File "/ibex/scratch/medinils/breast_data/env/lib/python3.8/site-packages/tornado/web.py", line 1786, in _execute
        result = await result
      File "/ibex/scratch/medinils/breast_data/env/lib/python3.8/site-packages/jupyter_server/services/contents/handlers.py", line 121, in get
        model = await ensure_async(
      File "/ibex/scratch/medinils/breast_data/env/lib/python3.8/site-packages/jupyter_core/utils/__init__.py", line 182, in ensure_async
        result = await obj
      File "/ibex/scratch/medinils/breast_data/env/lib/python3.8/site-packages/jupyter_server/services/contents/filemanager.py", line 861, in get
        raise web.HTTPError(404, "No such file or directory: %s" % path)
    tornado.web.HTTPError: HTTP 404: Not Found (No such file or directory: Scanpy/data)
[W 2023-08-18 04:54:57.783 ServerApp] 404 GET /api/contents/Scanpy/data?1692323697190 (e0cff5c1e766474f9e8aa8d378d5b591@10.109.65.8) 49.70ms referer=http://127.0.0.1:12815/lab
[I 2023-08-18 04:55:30.856 ServerApp] Creating new notebook in 
[I 2023-08-18 04:55:35.358 ServerApp] Kernel started: fd55227f-a2b8-4f04-afd9-ef67da8c0065
[I 2023-08-18 04:56:20.878 ServerApp] Connecting to kernel fd55227f-a2b8-4f04-afd9-ef67da8c0065.
[I 2023-08-18 04:56:21.770 ServerApp] Connecting to kernel fd55227f-a2b8-4f04-afd9-ef67da8c0065.
[I 2023-08-18 04:56:22.529 ServerApp] Connecting to kernel fd55227f-a2b8-4f04-afd9-ef67da8c0065.
[I 2023-08-18 04:57:33.331 ServerApp] Saving file at /Untitled.ipynb
[I 2023-08-18 05:01:34.487 ServerApp] Saving file at /Untitled.ipynb
[I 2023-08-18 05:03:36.346 ServerApp] Saving file at /Untitled.ipynb
[I 2023-08-18 05:07:58.372 ServerApp] Starting buffering for fd55227f-a2b8-4f04-afd9-ef67da8c0065:dc573be7-f3ef-4787-b64f-627917499bda
srun: Job step aborted: Waiting up to 32 seconds for job step to finish.
slurmstepd: error: *** STEP 26992755.0 ON cn605-21-l CANCELLED AT 2023-08-18T05:08:12 ***
slurmstepd: error: *** JOB 26992755 ON cn605-21-l CANCELLED AT 2023-08-18T05:08:12 ***
