/ibex/scratch/medinils/breast_data/bin/launch-jupyter-server.srun: line 7: S: command not found

To connect to the compute node  on Ibex running your Jupyter server, 
you need to create an ssh tunnel from your local machine to login node on Ibex 
using the following command.

ssh -L 12501:cn506-18-r:12501 medinils@ilogin.ibex.kaust.edu.sa 

Next, you need to copy the second url provided below and paste it into the browser 
on your local machine.

[I 2023-08-22 07:24:30.356 ServerApp] Package jupyterlab took 0.0000s to import
[I 2023-08-22 07:24:50.413 ServerApp] Package dask_labextension took 20.0568s to import
[W 2023-08-22 07:24:50.413 ServerApp] A `_jupyter_server_extension_points` function was not found in dask_labextension. Instead, a `_jupyter_server_extension_paths` function was found and will be used for now. This function name will be deprecated in future releases of Jupyter Server.
[I 2023-08-22 07:24:51.352 ServerApp] Package jupyter_lsp took 0.9377s to import
[W 2023-08-22 07:24:51.352 ServerApp] A `_jupyter_server_extension_points` function was not found in jupyter_lsp. Instead, a `_jupyter_server_extension_paths` function was found and will be used for now. This function name will be deprecated in future releases of Jupyter Server.
[I 2023-08-22 07:24:51.432 ServerApp] Package jupyter_server_fileid took 0.0803s to import
[I 2023-08-22 07:24:51.522 ServerApp] Package jupyter_server_mathjax took 0.0883s to import
[I 2023-08-22 07:24:51.522 ServerApp] Package jupyter_server_proxy took 0.0000s to import
[I 2023-08-22 07:24:51.847 ServerApp] Package jupyter_server_terminals took 0.3245s to import
[I 2023-08-22 07:24:54.763 ServerApp] Package jupyter_server_ydoc took 2.9153s to import
[I 2023-08-22 07:24:55.859 ServerApp] Package jupyterlab_git took 1.0946s to import
[I 2023-08-22 07:24:55.859 ServerApp] Package nbclassic took 0.0000s to import
[W 2023-08-22 07:24:55.958 ServerApp] A `_jupyter_server_extension_points` function was not found in nbclassic. Instead, a `_jupyter_server_extension_paths` function was found and will be used for now. This function name will be deprecated in future releases of Jupyter Server.
[I 2023-08-22 07:24:55.959 ServerApp] Package nbdime took 0.0000s to import
[I 2023-08-22 07:24:55.959 ServerApp] Package notebook_shim took 0.0000s to import
[W 2023-08-22 07:24:55.959 ServerApp] A `_jupyter_server_extension_points` function was not found in notebook_shim. Instead, a `_jupyter_server_extension_paths` function was found and will be used for now. This function name will be deprecated in future releases of Jupyter Server.
[I 2023-08-22 07:25:26.565 ServerApp] Package panel.io.jupyter_server_extension took 30.5751s to import
[I 2023-08-22 07:25:26.566 ServerApp] dask_labextension | extension was successfully linked.
[I 2023-08-22 07:25:26.566 ServerApp] jupyter_lsp | extension was successfully linked.
[I 2023-08-22 07:25:26.703 ServerApp] jupyter_server_fileid | extension was successfully linked.
[I 2023-08-22 07:25:26.832 ServerApp] jupyter_server_mathjax | extension was successfully linked.
[I 2023-08-22 07:25:26.833 ServerApp] jupyter_server_proxy | extension was successfully linked.
[I 2023-08-22 07:25:26.954 ServerApp] jupyter_server_terminals | extension was successfully linked.
[I 2023-08-22 07:25:27.077 ServerApp] jupyter_server_ydoc | extension was successfully linked.
[I 2023-08-22 07:25:27.204 ServerApp] jupyterlab | extension was successfully linked.
[I 2023-08-22 07:25:27.204 ServerApp] jupyterlab_git | extension was successfully linked.
[I 2023-08-22 07:25:27.324 ServerApp] nbclassic | extension was successfully linked.
[I 2023-08-22 07:25:27.324 ServerApp] nbdime | extension was successfully linked.
[I 2023-08-22 07:25:34.620 ServerApp] notebook_shim | extension was successfully linked.
[I 2023-08-22 07:25:34.621 ServerApp] panel.io.jupyter_server_extension | extension was successfully linked.
[I 2023-08-22 07:25:37.662 ServerApp] notebook_shim | extension was successfully loaded.
[I 2023-08-22 07:25:37.664 ServerApp] dask_labextension | extension was successfully loaded.
[I 2023-08-22 07:25:37.682 ServerApp] jupyter_lsp | extension was successfully loaded.
[I 2023-08-22 07:25:37.682 FileIdExtension] Configured File ID manager: ArbitraryFileIdManager
[I 2023-08-22 07:25:37.683 FileIdExtension] ArbitraryFileIdManager : Configured root dir: /ibex/scratch/medinils/breast_data
[I 2023-08-22 07:25:37.683 FileIdExtension] ArbitraryFileIdManager : Configured database path: /home/medinils/.local/share/jupyter/file_id_manager.db
[I 2023-08-22 07:25:37.685 FileIdExtension] ArbitraryFileIdManager : Successfully connected to database file.
[I 2023-08-22 07:25:37.685 FileIdExtension] ArbitraryFileIdManager : Creating File ID tables and indices with journal_mode = DELETE
[I 2023-08-22 07:25:37.687 FileIdExtension] Attached event listeners.
[I 2023-08-22 07:25:37.687 ServerApp] jupyter_server_fileid | extension was successfully loaded.
[I 2023-08-22 07:25:37.688 ServerApp] jupyter_server_mathjax | extension was successfully loaded.
[I 2023-08-22 07:25:38.889 ServerApp] jupyter_server_proxy | extension was successfully loaded.
[I 2023-08-22 07:25:38.896 ServerApp] jupyter_server_terminals | extension was successfully loaded.
[I 2023-08-22 07:25:38.897 ServerApp] jupyter_server_ydoc | extension was successfully loaded.
[I 2023-08-22 07:25:39.202 LabApp] JupyterLab extension loaded from /ibex/scratch/medinils/breast_data/env/lib/python3.8/site-packages/jupyterlab
[I 2023-08-22 07:25:39.202 LabApp] JupyterLab application directory is /ibex/scratch/medinils/breast_data/env/share/jupyter/lab
[I 2023-08-22 07:25:39.229 ServerApp] jupyterlab | extension was successfully loaded.
[I 2023-08-22 07:25:39.239 ServerApp] jupyterlab_git | extension was successfully loaded.
[I 2023-08-22 07:25:41.427 ServerApp] nbclassic | extension was successfully loaded.
[I 2023-08-22 07:25:43.455 ServerApp] nbdime | extension was successfully loaded.
[I 2023-08-22 07:25:43.456 ServerApp] panel.io.jupyter_server_extension | extension was successfully loaded.
[I 2023-08-22 07:25:43.458 ServerApp] Serving notebooks from local directory: /ibex/scratch/medinils/breast_data
[I 2023-08-22 07:25:43.458 ServerApp] Jupyter Server 2.7.1 is running at:
[I 2023-08-22 07:25:43.458 ServerApp] http://cn506-18-r:12501/lab?token=00b71412f4ee85fac3eeb1b866b1f9c7b91dd0b1dfecd774
[I 2023-08-22 07:25:43.458 ServerApp]     http://127.0.0.1:12501/lab?token=00b71412f4ee85fac3eeb1b866b1f9c7b91dd0b1dfecd774
[I 2023-08-22 07:25:43.458 ServerApp] Use Control-C to stop this server and shut down all kernels (twice to skip confirmation).
[C 2023-08-22 07:25:43.477 ServerApp] 
    
    To access the server, open this file in a browser:
        file:///home/medinils/.local/share/jupyter/runtime/jpserver-165716-open.html
    Or copy and paste one of these URLs:
        http://cn506-18-r:12501/lab?token=00b71412f4ee85fac3eeb1b866b1f9c7b91dd0b1dfecd774
        http://127.0.0.1:12501/lab?token=00b71412f4ee85fac3eeb1b866b1f9c7b91dd0b1dfecd774
[I 2023-08-22 07:25:45.169 ServerApp] Skipped non-installed server(s): bash-language-server, dockerfile-language-server-nodejs, javascript-typescript-langserver, jedi-language-server, julia-language-server, pyright, python-lsp-server, r-languageserver, sql-language-server, texlab, typescript-language-server, unified-language-server, vscode-css-languageserver-bin, vscode-html-languageserver-bin, vscode-json-languageserver-bin, yaml-language-server
[W 2023-08-22 07:30:07.743 LabApp] Could not determine jupyterlab build status without nodejs
[I 2023-08-22 07:30:54.065 ServerApp] Kernel started: 8c1d6647-5850-4b00-916d-1ff4bb002392
[XPythonShellApp] WARNING | Unrecognized alias: 'f', it will have no effect.
[I 2023-08-22 07:31:05.926 ServerApp] Connecting to kernel 8c1d6647-5850-4b00-916d-1ff4bb002392.
[I 2023-08-22 07:31:06.670 ServerApp] Starting buffering for 8c1d6647-5850-4b00-916d-1ff4bb002392:b5fc477c-5664-4b63-86c4-cd047bbd8701
[I 2023-08-22 07:31:06.705 ServerApp] Connecting to kernel 8c1d6647-5850-4b00-916d-1ff4bb002392.
[I 2023-08-22 07:31:07.456 ServerApp] Connecting to kernel 8c1d6647-5850-4b00-916d-1ff4bb002392.
Error: signal 11:
/ibex/scratch/medinils/breast_data/env/bin/../lib/libxeus-python.so.0(_ZN4xpyt15sigsegv_handlerEi+0x2b)[0x2b1ecb40e24b]
/lib64/libc.so.6(+0x36400)[0x2b1ecbda1400]
/ibex/scratch/medinils/breast_data/env/lib/python3.8/site-packages/torch/lib/libtorch_cpu.so(+0x1b081d5)[0x2b1f3aabb1d5]
/ibex/scratch/medinils/breast_data/env/lib/python3.8/site-packages/torch/lib/libtorch_cpu.so(_ZN3c106detail12infer_schema20make_function_schemaEOSsS2_NS_8ArrayRefINS1_11ArgumentDefEEES5_+0x43)[0x2b1f3aabb733]
/ibex/scratch/medinils/breast_data/env/lib/python3.8/site-packages/torch/lib/libtorch_cpu.so(_ZN3c106detail12infer_schema20make_function_schemaENS_8ArrayRefINS1_11ArgumentDefEEES4_+0x6d)[0x2b1f3aabbc0d]
/ibex/scratch/medinils/breast_data/env/lib/python3.8/site-packages/torch_cluster/_version_cpu.so(_ZNO3c1017RegisterOperators2opIFlvEEENSt9enable_ifIXaasrNS_4guts16is_function_typeIT_EE5valuentsrSt7is_sameIS6_FvRKNS_14OperatorHandleEPSt6vectorINS_6IValueESaISD_EEEE5valueEOS0_E4typeERKSsPS6_ONS0_7OptionsE+0x60)[0x2b1f9b1ec610]
/ibex/scratch/medinils/breast_data/env/lib/python3.8/site-packages/torch_cluster/_version_cpu.so(+0x3ce2)[0x2b1f9b1e7ce2]
/lib64/ld-linux-x86-64.so.2(+0xf9c3)[0x2b1ecb3619c3]
/lib64/ld-linux-x86-64.so.2(+0x1459e)[0x2b1ecb36659e]
/lib64/ld-linux-x86-64.so.2(+0xf7d4)[0x2b1ecb3617d4]
[I 2023-08-22 07:31:51.034 ServerApp] AsyncIOLoopKernelRestarter: restarting kernel (1/5), keep random ports
[W 2023-08-22 07:31:51.035 ServerApp] kernel 8c1d6647-5850-4b00-916d-1ff4bb002392 restarted
[W 2023-08-22 07:31:51.035 ServerApp] kernel 8c1d6647-5850-4b00-916d-1ff4bb002392 restarted
[I 2023-08-22 07:31:51.421 ServerApp] Starting buffering for 8c1d6647-5850-4b00-916d-1ff4bb002392:def0ff7a-765c-493d-999b-b88c381773d5
[I 2023-08-22 07:31:51.805 ServerApp] Connecting to kernel 8c1d6647-5850-4b00-916d-1ff4bb002392.
[I 2023-08-22 07:31:52.560 ServerApp] Connecting to kernel 8c1d6647-5850-4b00-916d-1ff4bb002392.
[W 2023-08-22 07:31:56.318 ServerApp] Nudge: attempt 10 on kernel 8c1d6647-5850-4b00-916d-1ff4bb002392
[W 2023-08-22 07:31:57.078 ServerApp] Nudge: attempt 10 on kernel 8c1d6647-5850-4b00-916d-1ff4bb002392
[W 2023-08-22 07:32:01.331 ServerApp] Nudge: attempt 20 on kernel 8c1d6647-5850-4b00-916d-1ff4bb002392
[W 2023-08-22 07:32:02.091 ServerApp] Nudge: attempt 20 on kernel 8c1d6647-5850-4b00-916d-1ff4bb002392
[XPythonShellApp] WARNING | Unrecognized alias: 'f', it will have no effect.
ERROR: received bad message: No such comm registered: db28d5d5-6709-4773-8071-7e04e0e479be
Message type: comm_msg
[I 2023-08-22 07:32:35.578 ServerApp] Saving file at /notebooks/challenge.ipynb
[I 2023-08-22 07:32:40.202 ServerApp] Kernel interrupted: 8c1d6647-5850-4b00-916d-1ff4bb002392
[I 2023-08-22 07:32:42.073 ServerApp] AsyncIOLoopKernelRestarter: restarting kernel (1/5), keep random ports
[W 2023-08-22 07:32:42.073 ServerApp] kernel 8c1d6647-5850-4b00-916d-1ff4bb002392 restarted
[W 2023-08-22 07:32:42.073 ServerApp] kernel 8c1d6647-5850-4b00-916d-1ff4bb002392 restarted
[I 2023-08-22 07:32:42.471 ServerApp] Starting buffering for 8c1d6647-5850-4b00-916d-1ff4bb002392:def0ff7a-765c-493d-999b-b88c381773d5
[I 2023-08-22 07:32:42.847 ServerApp] Connecting to kernel 8c1d6647-5850-4b00-916d-1ff4bb002392.
[I 2023-08-22 07:32:43.676 ServerApp] Connecting to kernel 8c1d6647-5850-4b00-916d-1ff4bb002392.
[W 2023-08-22 07:32:47.360 ServerApp] Nudge: attempt 10 on kernel 8c1d6647-5850-4b00-916d-1ff4bb002392
[W 2023-08-22 07:32:48.186 ServerApp] Nudge: attempt 10 on kernel 8c1d6647-5850-4b00-916d-1ff4bb002392
[W 2023-08-22 07:32:52.371 ServerApp] Nudge: attempt 20 on kernel 8c1d6647-5850-4b00-916d-1ff4bb002392
[W 2023-08-22 07:32:53.199 ServerApp] Nudge: attempt 20 on kernel 8c1d6647-5850-4b00-916d-1ff4bb002392
[XPythonShellApp] WARNING | Unrecognized alias: 'f', it will have no effect.
ERROR: received bad message: No such comm registered: e6f78ec2-7634-44f2-bff6-be57632c4880
Message type: comm_msg
2023-08-22 07:34:42,639 UTC - ERROR - pyls.plugins.pylint_lint - Error calling pylint: '<string>:1: DeprecationWarning: 'epylint' will be removed in pylint 3.0, use https://github.com/emacsorphanage/pylint instead.
'
Error: signal 11:
/ibex/scratch/medinils/breast_data/env/bin/../lib/libxeus-python.so.0(_ZN4xpyt15sigsegv_handlerEi+0x2b)[0x2b4535df824b]
/lib64/libc.so.6(+0x36400)[0x2b453678b400]
/ibex/scratch/medinils/breast_data/env/lib/python3.8/site-packages/torch/lib/libtorch_cpu.so(+0x1b081d5)[0x2b45a57dc1d5]
/ibex/scratch/medinils/breast_data/env/lib/python3.8/site-packages/torch/lib/libtorch_cpu.so(_ZN3c106detail12infer_schema20make_function_schemaEOSsS2_NS_8ArrayRefINS1_11ArgumentDefEEES5_+0x43)[0x2b45a57dc733]
/ibex/scratch/medinils/breast_data/env/lib/python3.8/site-packages/torch/lib/libtorch_cpu.so(_ZN3c106detail12infer_schema20make_function_schemaENS_8ArrayRefINS1_11ArgumentDefEEES4_+0x6d)[0x2b45a57dcc0d]
/ibex/scratch/medinils/breast_data/env/lib/python3.8/site-packages/torch_cluster/_version_cpu.so(_ZNO3c1017RegisterOperators2opIFlvEEENSt9enable_ifIXaasrNS_4guts16is_function_typeIT_EE5valuentsrSt7is_sameIS6_FvRKNS_14OperatorHandleEPSt6vectorINS_6IValueESaISD_EEEE5valueEOS0_E4typeERKSsPS6_ONS0_7OptionsE+0x60)[0x2b4605bf8610]
/ibex/scratch/medinils/breast_data/env/lib/python3.8/site-packages/torch_cluster/_version_cpu.so(+0x3ce2)[0x2b4605bf3ce2]
/lib64/ld-linux-x86-64.so.2(+0xf9c3)[0x2b4535d4b9c3]
/lib64/ld-linux-x86-64.so.2(+0x1459e)[0x2b4535d5059e]
/lib64/ld-linux-x86-64.so.2(+0xf7d4)[0x2b4535d4b7d4]
[I 2023-08-22 07:36:27.108 ServerApp] AsyncIOLoopKernelRestarter: restarting kernel (1/5), keep random ports
[W 2023-08-22 07:36:27.108 ServerApp] kernel 8c1d6647-5850-4b00-916d-1ff4bb002392 restarted
[W 2023-08-22 07:36:27.108 ServerApp] kernel 8c1d6647-5850-4b00-916d-1ff4bb002392 restarted
[I 2023-08-22 07:36:27.476 ServerApp] Starting buffering for 8c1d6647-5850-4b00-916d-1ff4bb002392:f4e3348c-a6c4-479c-8a10-7450532f37ee
[I 2023-08-22 07:36:27.854 ServerApp] Connecting to kernel 8c1d6647-5850-4b00-916d-1ff4bb002392.
[I 2023-08-22 07:36:28.627 ServerApp] Connecting to kernel 8c1d6647-5850-4b00-916d-1ff4bb002392.
[I 2023-08-22 07:36:37.048 ServerApp] Saving file at /notebooks/challenge.ipynb
[XPythonShellApp] WARNING | Unrecognized alias: 'f', it will have no effect.
ERROR: received bad message: No such comm registered: 91c96f93-5762-40c4-80c0-c6befb49e8bd
Message type: comm_msg
[I 2023-08-22 07:36:49.752 ServerApp] Kernel started: b6df703a-7a1d-4741-a863-452c39ed1b52
[I 2023-08-22 07:36:49.753 ServerApp] Kernel shutdown: 8c1d6647-5850-4b00-916d-1ff4bb002392
ERROR: Signatures don't match
[I 2023-08-22 07:37:18.572 ServerApp] Connecting to kernel b6df703a-7a1d-4741-a863-452c39ed1b52.
[I 2023-08-22 07:37:19.340 ServerApp] Connecting to kernel b6df703a-7a1d-4741-a863-452c39ed1b52.
[I 2023-08-22 07:37:20.190 ServerApp] Connecting to kernel b6df703a-7a1d-4741-a863-452c39ed1b52.
[I 2023-08-22 07:38:01.728 ServerApp] AsyncIOLoopKernelRestarter: restarting kernel (1/5), keep random ports
[W 2023-08-22 07:38:01.728 ServerApp] kernel b6df703a-7a1d-4741-a863-452c39ed1b52 restarted
[W 2023-08-22 07:38:01.729 ServerApp] kernel b6df703a-7a1d-4741-a863-452c39ed1b52 restarted
[W 2023-08-22 07:38:01.729 ServerApp] kernel b6df703a-7a1d-4741-a863-452c39ed1b52 restarted
[I 2023-08-22 07:38:02.108 ServerApp] Starting buffering for b6df703a-7a1d-4741-a863-452c39ed1b52:def0ff7a-765c-493d-999b-b88c381773d5
[I 2023-08-22 07:38:02.485 ServerApp] Connecting to kernel b6df703a-7a1d-4741-a863-452c39ed1b52.
[I 2023-08-22 07:38:02.485 ServerApp] Restoring connection for b6df703a-7a1d-4741-a863-452c39ed1b52:def0ff7a-765c-493d-999b-b88c381773d5
[I 2023-08-22 07:38:03.247 ServerApp] Connecting to kernel b6df703a-7a1d-4741-a863-452c39ed1b52.
[I 2023-08-22 07:38:03.999 ServerApp] Connecting to kernel b6df703a-7a1d-4741-a863-452c39ed1b52.
[W 2023-08-22 07:38:06.996 ServerApp] Nudge: attempt 10 on kernel b6df703a-7a1d-4741-a863-452c39ed1b52
[W 2023-08-22 07:38:07.762 ServerApp] Nudge: attempt 10 on kernel b6df703a-7a1d-4741-a863-452c39ed1b52
[W 2023-08-22 07:38:08.511 ServerApp] Nudge: attempt 10 on kernel b6df703a-7a1d-4741-a863-452c39ed1b52
[W 2023-08-22 07:38:12.010 ServerApp] Nudge: attempt 20 on kernel b6df703a-7a1d-4741-a863-452c39ed1b52
[W 2023-08-22 07:38:12.777 ServerApp] Nudge: attempt 20 on kernel b6df703a-7a1d-4741-a863-452c39ed1b52
[W 2023-08-22 07:38:13.525 ServerApp] Nudge: attempt 20 on kernel b6df703a-7a1d-4741-a863-452c39ed1b52
[W 2023-08-22 07:38:17.024 ServerApp] Nudge: attempt 30 on kernel b6df703a-7a1d-4741-a863-452c39ed1b52
[W 2023-08-22 07:38:17.792 ServerApp] Nudge: attempt 30 on kernel b6df703a-7a1d-4741-a863-452c39ed1b52
[W 2023-08-22 07:38:18.540 ServerApp] Nudge: attempt 30 on kernel b6df703a-7a1d-4741-a863-452c39ed1b52
[W 2023-08-22 07:38:22.038 ServerApp] Nudge: attempt 40 on kernel b6df703a-7a1d-4741-a863-452c39ed1b52
[W 2023-08-22 07:38:22.805 ServerApp] Nudge: attempt 40 on kernel b6df703a-7a1d-4741-a863-452c39ed1b52
[W 2023-08-22 07:38:23.553 ServerApp] Nudge: attempt 40 on kernel b6df703a-7a1d-4741-a863-452c39ed1b52
[W 2023-08-22 07:38:27.051 ServerApp] Nudge: attempt 50 on kernel b6df703a-7a1d-4741-a863-452c39ed1b52
[W 2023-08-22 07:38:27.819 ServerApp] Nudge: attempt 50 on kernel b6df703a-7a1d-4741-a863-452c39ed1b52
[W 2023-08-22 07:38:28.566 ServerApp] Nudge: attempt 50 on kernel b6df703a-7a1d-4741-a863-452c39ed1b52
[I 2023-08-22 07:38:38.528 ServerApp] Saving file at /notebooks/challenge.ipynb
2023-08-22 07:38:44,380 UTC - ERROR - pyls.plugins.pylint_lint - Error calling pylint: '<string>:1: DeprecationWarning: 'epylint' will be removed in pylint 3.0, use https://github.com/emacsorphanage/pylint instead.
'
2023-08-22 07:40:44,883 UTC - ERROR - pyls.plugins.pylint_lint - Error calling pylint: '<string>:1: DeprecationWarning: 'epylint' will be removed in pylint 3.0, use https://github.com/emacsorphanage/pylint instead.
'
[I 2023-08-22 07:40:46.493 ServerApp] Connecting to kernel b6df703a-7a1d-4741-a863-452c39ed1b52.
[I 2023-08-22 07:41:03.249 ServerApp] Connecting to kernel b6df703a-7a1d-4741-a863-452c39ed1b52.
[I 2023-08-22 07:41:12.403 ServerApp] Kernel interrupted: b6df703a-7a1d-4741-a863-452c39ed1b52
[I 2023-08-22 07:41:20.941 ServerApp] Kernel restarted: b6df703a-7a1d-4741-a863-452c39ed1b52
[I 2023-08-22 07:41:21.681 ServerApp] Connecting to kernel b6df703a-7a1d-4741-a863-452c39ed1b52.
[W 2023-08-22 07:41:26.197 ServerApp] Nudge: attempt 10 on kernel b6df703a-7a1d-4741-a863-452c39ed1b52
[W 2023-08-22 07:41:31.227 ServerApp] Nudge: attempt 20 on kernel b6df703a-7a1d-4741-a863-452c39ed1b52
[W 2023-08-22 07:41:36.239 ServerApp] Nudge: attempt 30 on kernel b6df703a-7a1d-4741-a863-452c39ed1b52
[W 2023-08-22 07:41:41.312 ServerApp] Nudge: attempt 40 on kernel b6df703a-7a1d-4741-a863-452c39ed1b52
[W 2023-08-22 07:41:46.326 ServerApp] Nudge: attempt 50 on kernel b6df703a-7a1d-4741-a863-452c39ed1b52
[I 2023-08-22 07:42:05.771 ServerApp] Kernel started: e5fa325f-c32a-43eb-a03c-663dba21a060
[I 2023-08-22 07:42:05.772 ServerApp] Kernel shutdown: b6df703a-7a1d-4741-a863-452c39ed1b52
[XPythonShellApp] WARNING | Unrecognized alias: 'f', it will have no effect.
[I 2023-08-22 07:42:17.739 ServerApp] Connecting to kernel e5fa325f-c32a-43eb-a03c-663dba21a060.
ERROR: received bad message: No such comm registered: a85c1eae-0e9e-4fcb-b9e7-e1e4b9ca5874
Message type: comm_msg
[I 2023-08-22 07:42:18.498 ServerApp] Connecting to kernel e5fa325f-c32a-43eb-a03c-663dba21a060.
[I 2023-08-22 07:42:40.226 ServerApp] Saving file at /notebooks/challenge.ipynb
Error: signal 11:
/ibex/scratch/medinils/breast_data/env/bin/../lib/libxeus-python.so.0(_ZN4xpyt15sigsegv_handlerEi+0x2b)[0x2b6e4dd7524b]
/lib64/libc.so.6(+0x36400)[0x2b6e4e708400]
/ibex/scratch/medinils/breast_data/env/lib/python3.8/site-packages/torch/lib/libtorch_cpu.so(+0x1b081d5)[0x2b6ebd7dc1d5]
/ibex/scratch/medinils/breast_data/env/lib/python3.8/site-packages/torch/lib/libtorch_cpu.so(_ZN3c106detail12infer_schema20make_function_schemaEOSsS2_NS_8ArrayRefINS1_11ArgumentDefEEES5_+0x43)[0x2b6ebd7dc733]
/ibex/scratch/medinils/breast_data/env/lib/python3.8/site-packages/torch/lib/libtorch_cpu.so(_ZN3c106detail12infer_schema20make_function_schemaENS_8ArrayRefINS1_11ArgumentDefEEES4_+0x6d)[0x2b6ebd7dcc0d]
/ibex/scratch/medinils/breast_data/env/lib/python3.8/site-packages/torch_cluster/_version_cpu.so(_ZNO3c1017RegisterOperators2opIFlvEEENSt9enable_ifIXaasrNS_4guts16is_function_typeIT_EE5valuentsrSt7is_sameIS6_FvRKNS_14OperatorHandleEPSt6vectorINS_6IValueESaISD_EEEE5valueEOS0_E4typeERKSsPS6_ONS0_7OptionsE+0x60)[0x2b6f1decd610]
/ibex/scratch/medinils/breast_data/env/lib/python3.8/site-packages/torch_cluster/_version_cpu.so(+0x3ce2)[0x2b6f1dec8ce2]
/lib64/ld-linux-x86-64.so.2(+0xf9c3)[0x2b6e4dcc89c3]
/lib64/ld-linux-x86-64.so.2(+0x1459e)[0x2b6e4dccd59e]
/lib64/ld-linux-x86-64.so.2(+0xf7d4)[0x2b6e4dcc87d4]
[I 2023-08-22 07:44:02.747 ServerApp] AsyncIOLoopKernelRestarter: restarting kernel (1/5), keep random ports
[W 2023-08-22 07:44:02.747 ServerApp] kernel e5fa325f-c32a-43eb-a03c-663dba21a060 restarted
[W 2023-08-22 07:44:02.747 ServerApp] kernel e5fa325f-c32a-43eb-a03c-663dba21a060 restarted
[I 2023-08-22 07:44:03.116 ServerApp] Starting buffering for e5fa325f-c32a-43eb-a03c-663dba21a060:def0ff7a-765c-493d-999b-b88c381773d5
[I 2023-08-22 07:44:03.499 ServerApp] Connecting to kernel e5fa325f-c32a-43eb-a03c-663dba21a060.
[I 2023-08-22 07:44:04.253 ServerApp] Connecting to kernel e5fa325f-c32a-43eb-a03c-663dba21a060.
[XPythonShellApp] WARNING | Unrecognized alias: 'f', it will have no effect.
ERROR: received bad message: No such comm registered: 4a443bca-45f8-47f6-b766-347b0dc4d915
Message type: comm_msg
[I 2023-08-22 07:44:41.631 ServerApp] Saving file at /notebooks/challenge.ipynb
2023-08-22 07:44:51,514 UTC - ERROR - pyls.plugins.pylint_lint - Error calling pylint: '<string>:1: DeprecationWarning: 'epylint' will be removed in pylint 3.0, use https://github.com/emacsorphanage/pylint instead.
'
Error: signal 11:
/ibex/scratch/medinils/breast_data/env/bin/../lib/libxeus-python.so.0(_ZN4xpyt15sigsegv_handlerEi+0x2b)[0x2acbdc4ce24b]
/lib64/libc.so.6(+0x36400)[0x2acbdce61400]
/ibex/scratch/medinils/breast_data/env/lib/python3.8/site-packages/torch/lib/libtorch_cpu.so(+0x1b081d5)[0x2acc4bb341d5]
/ibex/scratch/medinils/breast_data/env/lib/python3.8/site-packages/torch/lib/libtorch_cpu.so(_ZN3c106detail12infer_schema20make_function_schemaEOSsS2_NS_8ArrayRefINS1_11ArgumentDefEEES5_+0x43)[0x2acc4bb34733]
/ibex/scratch/medinils/breast_data/env/lib/python3.8/site-packages/torch/lib/libtorch_cpu.so(_ZN3c106detail12infer_schema20make_function_schemaENS_8ArrayRefINS1_11ArgumentDefEEES4_+0x6d)[0x2acc4bb34c0d]
/ibex/scratch/medinils/breast_data/env/lib/python3.8/site-packages/torch_cluster/_version_cpu.so(_ZNO3c1017RegisterOperators2opIFlvEEENSt9enable_ifIXaasrNS_4guts16is_function_typeIT_EE5valuentsrSt7is_sameIS6_FvRKNS_14OperatorHandleEPSt6vectorINS_6IValueESaISD_EEEE5valueEOS0_E4typeERKSsPS6_ONS0_7OptionsE+0x60)[0x2accad852610]
/ibex/scratch/medinils/breast_data/env/lib/python3.8/site-packages/torch_cluster/_version_cpu.so(+0x3ce2)[0x2accad84dce2]
/lib64/ld-linux-x86-64.so.2(+0xf9c3)[0x2acbdc4219c3]
/lib64/ld-linux-x86-64.so.2(+0x1459e)[0x2acbdc42659e]
/lib64/ld-linux-x86-64.so.2(+0xf7d4)[0x2acbdc4217d4]
[I 2023-08-22 07:45:59.782 ServerApp] AsyncIOLoopKernelRestarter: restarting kernel (1/5), keep random ports
[W 2023-08-22 07:45:59.782 ServerApp] kernel e5fa325f-c32a-43eb-a03c-663dba21a060 restarted
[W 2023-08-22 07:45:59.782 ServerApp] kernel e5fa325f-c32a-43eb-a03c-663dba21a060 restarted
[I 2023-08-22 07:46:00.246 ServerApp] Starting buffering for e5fa325f-c32a-43eb-a03c-663dba21a060:f4e3348c-a6c4-479c-8a10-7450532f37ee
[I 2023-08-22 07:46:00.661 ServerApp] Connecting to kernel e5fa325f-c32a-43eb-a03c-663dba21a060.
[I 2023-08-22 07:46:01.476 ServerApp] Connecting to kernel e5fa325f-c32a-43eb-a03c-663dba21a060.
[XPythonShellApp] WARNING | Unrecognized alias: 'f', it will have no effect.
[I 2023-08-22 07:46:43.294 ServerApp] Saving file at /notebooks/challenge.ipynb
2023-08-22 07:46:45,355 UTC - ERROR - pyls.plugins.pylint_lint - Error calling pylint: '<string>:1: DeprecationWarning: 'epylint' will be removed in pylint 3.0, use https://github.com/emacsorphanage/pylint instead.
'
2023-08-22 07:48:49,385 UTC - ERROR - pyls.plugins.pylint_lint - Error calling pylint: '<string>:1: DeprecationWarning: 'epylint' will be removed in pylint 3.0, use https://github.com/emacsorphanage/pylint instead.
'
[I 2023-08-22 07:52:44.530 ServerApp] Saving file at /notebooks/challenge.ipynb
[E 2023-08-22 07:53:32.906 ServerApp.jupyterlab_git] Error computing notebook diff.
    Traceback (most recent call last):
      File "/ibex/scratch/medinils/breast_data/env/lib/python3.8/site-packages/nbformat/reader.py", line 20, in parse_json
        nb_dict = json.loads(s, **kwargs)
      File "/ibex/scratch/medinils/breast_data/env/lib/python3.8/json/__init__.py", line 357, in loads
        return _default_decoder.decode(s)
      File "/ibex/scratch/medinils/breast_data/env/lib/python3.8/json/decoder.py", line 337, in decode
        obj, end = self.raw_decode(s, idx=_w(s, 0).end())
      File "/ibex/scratch/medinils/breast_data/env/lib/python3.8/json/decoder.py", line 355, in raw_decode
        raise JSONDecodeError("Expecting value", s, err.value) from None
    json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)
    
    The above exception was the direct cause of the following exception:
    
    Traceback (most recent call last):
      File "/ibex/scratch/medinils/breast_data/env/lib/python3.8/site-packages/jupyterlab_git/handlers.py", line 796, in post
        content = await self.git.get_nbdiff(
      File "/ibex/scratch/medinils/breast_data/env/lib/python3.8/site-packages/jupyterlab_git/git.py", line 462, in get_nbdiff
        curr_nb = await current_loop.run_in_executor(None, read_notebook, curr_content)
      File "/ibex/scratch/medinils/breast_data/env/lib/python3.8/concurrent/futures/thread.py", line 57, in run
        result = self.fn(*self.args, **self.kwargs)
      File "/ibex/scratch/medinils/breast_data/env/lib/python3.8/site-packages/jupyterlab_git/git.py", line 452, in read_notebook
        return nbformat.reads(content, as_version=4)
      File "/ibex/scratch/medinils/breast_data/env/lib/python3.8/site-packages/nbformat/__init__.py", line 89, in reads
        nb = reader.reads(s, **kwargs)
      File "/ibex/scratch/medinils/breast_data/env/lib/python3.8/site-packages/nbformat/reader.py", line 76, in reads
        nb_dict = parse_json(s, **kwargs)
      File "/ibex/scratch/medinils/breast_data/env/lib/python3.8/site-packages/nbformat/reader.py", line 26, in parse_json
        raise NotJSONError(message) from e
    nbformat.reader.NotJSONError: Notebook does not appear to be JSON: '####packages\nfrom pathlib import Path\...
[W 2023-08-22 07:53:33.055 ServerApp] wrote error: 'Internal Server Error'
    Traceback (most recent call last):
      File "/ibex/scratch/medinils/breast_data/env/lib/python3.8/site-packages/nbformat/reader.py", line 20, in parse_json
        nb_dict = json.loads(s, **kwargs)
      File "/ibex/scratch/medinils/breast_data/env/lib/python3.8/json/__init__.py", line 357, in loads
        return _default_decoder.decode(s)
      File "/ibex/scratch/medinils/breast_data/env/lib/python3.8/json/decoder.py", line 337, in decode
        obj, end = self.raw_decode(s, idx=_w(s, 0).end())
      File "/ibex/scratch/medinils/breast_data/env/lib/python3.8/json/decoder.py", line 355, in raw_decode
        raise JSONDecodeError("Expecting value", s, err.value) from None
    json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)
    
    The above exception was the direct cause of the following exception:
    
    Traceback (most recent call last):
      File "/ibex/scratch/medinils/breast_data/env/lib/python3.8/site-packages/jupyterlab_git/handlers.py", line 796, in post
        content = await self.git.get_nbdiff(
      File "/ibex/scratch/medinils/breast_data/env/lib/python3.8/site-packages/jupyterlab_git/git.py", line 462, in get_nbdiff
        curr_nb = await current_loop.run_in_executor(None, read_notebook, curr_content)
      File "/ibex/scratch/medinils/breast_data/env/lib/python3.8/concurrent/futures/thread.py", line 57, in run
        result = self.fn(*self.args, **self.kwargs)
      File "/ibex/scratch/medinils/breast_data/env/lib/python3.8/site-packages/jupyterlab_git/git.py", line 452, in read_notebook
        return nbformat.reads(content, as_version=4)
      File "/ibex/scratch/medinils/breast_data/env/lib/python3.8/site-packages/nbformat/__init__.py", line 89, in reads
        nb = reader.reads(s, **kwargs)
      File "/ibex/scratch/medinils/breast_data/env/lib/python3.8/site-packages/nbformat/reader.py", line 76, in reads
        nb_dict = parse_json(s, **kwargs)
      File "/ibex/scratch/medinils/breast_data/env/lib/python3.8/site-packages/nbformat/reader.py", line 26, in parse_json
        raise NotJSONError(message) from e
    nbformat.reader.NotJSONError: Notebook does not appear to be JSON: '####packages\nfrom pathlib import Path\...
    
    The above exception was the direct cause of the following exception:
    
    Traceback (most recent call last):
      File "/ibex/scratch/medinils/breast_data/env/lib/python3.8/site-packages/tornado/web.py", line 1786, in _execute
        result = await result
      File "/ibex/scratch/medinils/breast_data/env/lib/python3.8/site-packages/jupyterlab_git/handlers.py", line 801, in post
        raise tornado.web.HTTPError(
    tornado.web.HTTPError: HTTP 500: Error diffing content: Notebook does not appear to be JSON: '####packages\nfrom pathlib import Path\....
[E 2023-08-22 07:53:33.109 ServerApp] {
      "Host": "127.0.0.1:12501",
      "Accept": "*/*",
      "Referer": "http://127.0.0.1:12501/lab",
      "User-Agent": "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/116.0.0.0 Safari/537.36"
    }
[E 2023-08-22 07:53:33.109 ServerApp] 500 POST /git/diffnotebook?1692680012318 (cce640d474034411868050e0da3c414a@10.109.65.7) 205.79ms referer=http://127.0.0.1:12501/lab
[E 2023-08-22 07:53:45.723 ServerApp.jupyterlab_git] Error computing notebook diff.
    Traceback (most recent call last):
      File "/ibex/scratch/medinils/breast_data/env/lib/python3.8/site-packages/nbformat/reader.py", line 20, in parse_json
        nb_dict = json.loads(s, **kwargs)
      File "/ibex/scratch/medinils/breast_data/env/lib/python3.8/json/__init__.py", line 357, in loads
        return _default_decoder.decode(s)
      File "/ibex/scratch/medinils/breast_data/env/lib/python3.8/json/decoder.py", line 337, in decode
        obj, end = self.raw_decode(s, idx=_w(s, 0).end())
      File "/ibex/scratch/medinils/breast_data/env/lib/python3.8/json/decoder.py", line 355, in raw_decode
        raise JSONDecodeError("Expecting value", s, err.value) from None
    json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)
    
    The above exception was the direct cause of the following exception:
    
    Traceback (most recent call last):
      File "/ibex/scratch/medinils/breast_data/env/lib/python3.8/site-packages/jupyterlab_git/handlers.py", line 796, in post
        content = await self.git.get_nbdiff(
      File "/ibex/scratch/medinils/breast_data/env/lib/python3.8/site-packages/jupyterlab_git/git.py", line 462, in get_nbdiff
        curr_nb = await current_loop.run_in_executor(None, read_notebook, curr_content)
      File "/ibex/scratch/medinils/breast_data/env/lib/python3.8/concurrent/futures/thread.py", line 57, in run
        result = self.fn(*self.args, **self.kwargs)
      File "/ibex/scratch/medinils/breast_data/env/lib/python3.8/site-packages/jupyterlab_git/git.py", line 452, in read_notebook
        return nbformat.reads(content, as_version=4)
      File "/ibex/scratch/medinils/breast_data/env/lib/python3.8/site-packages/nbformat/__init__.py", line 89, in reads
        nb = reader.reads(s, **kwargs)
      File "/ibex/scratch/medinils/breast_data/env/lib/python3.8/site-packages/nbformat/reader.py", line 76, in reads
        nb_dict = parse_json(s, **kwargs)
      File "/ibex/scratch/medinils/breast_data/env/lib/python3.8/site-packages/nbformat/reader.py", line 26, in parse_json
        raise NotJSONError(message) from e
    nbformat.reader.NotJSONError: Notebook does not appear to be JSON: '####packages\nfrom pathlib import Path\...
[W 2023-08-22 07:53:45.764 ServerApp] wrote error: 'Internal Server Error'
    Traceback (most recent call last):
      File "/ibex/scratch/medinils/breast_data/env/lib/python3.8/site-packages/nbformat/reader.py", line 20, in parse_json
        nb_dict = json.loads(s, **kwargs)
      File "/ibex/scratch/medinils/breast_data/env/lib/python3.8/json/__init__.py", line 357, in loads
        return _default_decoder.decode(s)
      File "/ibex/scratch/medinils/breast_data/env/lib/python3.8/json/decoder.py", line 337, in decode
        obj, end = self.raw_decode(s, idx=_w(s, 0).end())
      File "/ibex/scratch/medinils/breast_data/env/lib/python3.8/json/decoder.py", line 355, in raw_decode
        raise JSONDecodeError("Expecting value", s, err.value) from None
    json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)
    
    The above exception was the direct cause of the following exception:
    
    Traceback (most recent call last):
      File "/ibex/scratch/medinils/breast_data/env/lib/python3.8/site-packages/jupyterlab_git/handlers.py", line 796, in post
        content = await self.git.get_nbdiff(
      File "/ibex/scratch/medinils/breast_data/env/lib/python3.8/site-packages/jupyterlab_git/git.py", line 462, in get_nbdiff
        curr_nb = await current_loop.run_in_executor(None, read_notebook, curr_content)
      File "/ibex/scratch/medinils/breast_data/env/lib/python3.8/concurrent/futures/thread.py", line 57, in run
        result = self.fn(*self.args, **self.kwargs)
      File "/ibex/scratch/medinils/breast_data/env/lib/python3.8/site-packages/jupyterlab_git/git.py", line 452, in read_notebook
        return nbformat.reads(content, as_version=4)
      File "/ibex/scratch/medinils/breast_data/env/lib/python3.8/site-packages/nbformat/__init__.py", line 89, in reads
        nb = reader.reads(s, **kwargs)
      File "/ibex/scratch/medinils/breast_data/env/lib/python3.8/site-packages/nbformat/reader.py", line 76, in reads
        nb_dict = parse_json(s, **kwargs)
      File "/ibex/scratch/medinils/breast_data/env/lib/python3.8/site-packages/nbformat/reader.py", line 26, in parse_json
        raise NotJSONError(message) from e
    nbformat.reader.NotJSONError: Notebook does not appear to be JSON: '####packages\nfrom pathlib import Path\...
    
    The above exception was the direct cause of the following exception:
    
    Traceback (most recent call last):
      File "/ibex/scratch/medinils/breast_data/env/lib/python3.8/site-packages/tornado/web.py", line 1786, in _execute
        result = await result
      File "/ibex/scratch/medinils/breast_data/env/lib/python3.8/site-packages/jupyterlab_git/handlers.py", line 801, in post
        raise tornado.web.HTTPError(
    tornado.web.HTTPError: HTTP 500: Error diffing content: Notebook does not appear to be JSON: '####packages\nfrom pathlib import Path\....
[E 2023-08-22 07:53:45.811 ServerApp] {
      "Host": "127.0.0.1:12501",
      "Accept": "*/*",
      "Referer": "http://127.0.0.1:12501/lab",
      "User-Agent": "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/116.0.0.0 Safari/537.36"
    }
[E 2023-08-22 07:53:45.811 ServerApp] 500 POST /git/diffnotebook?1692680025136 (cce640d474034411868050e0da3c414a@10.109.65.7) 90.44ms referer=http://127.0.0.1:12501/lab
[I 2023-08-22 07:54:45.607 ServerApp] Saving file at /notebooks/challenge.ipynb
2023-08-22 07:56:45,300 UTC - ERROR - pyls.plugins.pylint_lint - Error calling pylint: '<string>:1: DeprecationWarning: 'epylint' will be removed in pylint 3.0, use https://github.com/emacsorphanage/pylint instead.
'
[I 2023-08-22 08:00:47.278 ServerApp] Saving file at /notebooks/challenge.ipynb
2023-08-22 08:01:06,272 UTC - ERROR - pyls.plugins.pylint_lint - Error calling pylint: '<string>:1: DeprecationWarning: 'epylint' will be removed in pylint 3.0, use https://github.com/emacsorphanage/pylint instead.
'
[I 2023-08-22 08:12:38.016 ServerApp] Starting buffering for e5fa325f-c32a-43eb-a03c-663dba21a060:def0ff7a-765c-493d-999b-b88c381773d5
srun: Job step aborted: Waiting up to 32 seconds for job step to finish.
slurmstepd: error: *** STEP 27042514.0 ON cn506-18-r CANCELLED AT 2023-08-22T08:12:59 ***
slurmstepd: error: *** JOB 27042514 ON cn506-18-r CANCELLED AT 2023-08-22T08:12:59 ***
